### ISSUE TITLE
Resumos marcados na medline?

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/MarkAbstract#5]
Aparentemente o resumo do documento http://pesquisa.bvsalud.org/portal/resource/pt/mdl-26377746 está bem estruturado para ser marcado automaticamente.

O processamento do MarkAbstract foi executado para Medline?

**Comment by botturam** [comment]
Preciso ver com o Heitor. XMLs e schemas estão preparados, mas parece que MEDLINE não está funcionando.

O campo "mark_ab" está gerado em /bases/iahx/proc/mdl5/main/xml.index/mdl15_regional.xml:
-rw-rw-r-- 1 tomcat operacao 8229660400 Oct 23 12:17 mdl15_regional.xml

e a data do último processamento é posterior:

serverofi5:/home/javaapps/iahx-server/indexes/solr5-port5/mdl5/data/mdl.index $ ll
total 369618092
-rw-rw-r-- 1 tomcat operacao          169 Oct 27 00:29 segments_eb5
-rw-rw-r-- 1 tomcat operacao  26351279024 Oct 26 20:39 _vsl.fdt
-rw-rw-r-- 1 tomcat operacao     10450598 Oct 26 20:39 _vsl.fdx
-rw-rw-r-- 1 tomcat operacao         5744 Oct 27 00:29 _vsl.fnm
-rw-rw-r-- 1 tomcat operacao  77790245596 Oct 26 23:16 _vsl_Lucene50_0.doc
-rw-rw-r-- 1 tomcat operacao 192930289939 Oct 26 23:16 _vsl_Lucene50_0.pos
-rw-rw-r-- 1 tomcat operacao   2251640551 Oct 26 23:16 _vsl_Lucene50_0.tim
-rw-rw-r-- 1 tomcat operacao     45254749 Oct 26 23:16 _vsl_Lucene50_0.tip
-rw-rw-r-- 1 tomcat operacao    487209619 Oct 26 23:16 _vsl.nvd
-rw-rw-r-- 1 tomcat operacao          268 Oct 26 23:16 _vsl.nvm
-rw-rw-r-- 1 tomcat operacao          535 Oct 27 00:29 _vsl.si
-rw-rw-r-- 1 tomcat operacao  78564953558 Oct 27 00:29 _vsl.tvd
-rw-rw-r-- 1 tomcat operacao     57450305 Oct 27 00:29 _vsl.tvx
-rw-rw-r-- 1 tomcat operacao            0 Oct 23 11:04 write.lock


<field name="mark_ab">&lt;h2&gt;INTRODUCTION:&lt;/h2&gt; The establishment of the rural clinical schools funded through the Commonwealth Department of Health and Ageing (now Department of Health) Rural Clinical Training and Support program over a decade ago has been a significant policy initiative in Australian rural health. This article explores the impacts of this policy initiative and presents the wide range of educational innovations contextualised to each rural community they serve.&lt;h2&gt;METHODS:&lt;/h2&gt; This article reviews the achievements of the Australian rural clinical and regional medical schools (RCS/RMS) through semi-structured interviews with the program directors or other key informants. The questions and responses were analysed according to the funding parameters to ascertain the numbers of students, types of student placements and range of activities undertaken by each university program.&lt;h2&gt;RESULTS:&lt;/h2&gt; Sixteen university medical schools have established 18 rural programs, creating an extensive national network of RCS and RMS in every state and territory. The findings reveal extensive positive impacts on rural and regional communities, curriculum innovation in medical education programs and community engagement activities. Teaching facilities, information technology, video-conferencing and student accommodation have brought new infrastructure to small rural towns. Rural clinicians are thriving on new opportunities for education and research. Clinicians continue to deliver clinical services and some have taken on formal academic positions, reducing professional isolation, improving the quality of care and their job satisfaction. This strategy has created many new clinical academics in rural areas, which has retained and expanded the clinical workforce. A total of 1224 students are provided with high-quality learning experiences for long-term clinical placements. These placements consist of a year or more in primary care, community and hospital settings across hundreds of rural and remote areas. Many programs offer longitudinal integrated clerkships; others offer block rotations in general practice and specialist clinics. Nine universities established programs prior to 2004, and these well-established programs are finding graduates who are returning to rural practice. Universities are required to have 25% of the students from a rural background. University admission policies have changed to encourage more applications from rural students. This aspect of the policy implements the extensive research evidence that rural-origin students are more likely to become rural practitioners. Additional capacity for research in RCS has influenced the rural health agenda in fields including epidemiology, population health, Aboriginal health, aged care, mental health and suicide prevention, farming families and climate change. There are strong research partnerships with rural workforce agencies, research centres for early career researchers and PhD students.&lt;h2&gt;CONCLUSIONS:&lt;/h2&gt; The RCS policy initiative has vastly increased opportunities for medical students to have long-term clinical placements in rural health services. Over a decade since the policy has been implemented, graduates are being attracted to rural practice because they have positive learning experiences, good infrastructure and support within rural areas. The study shows the RCS initiative sets the stage for a sustainable future Australian rural medical workforce now requiring the development of a seamless rural clinical training pipeline linking undergraduate and postgraduate medical education.</field>

**Comment by botturam** [comment]
alterações realizadas em serverofi5:/home/javaapps/iahx-server/indexes/solr5-port6/portal/conf/schema.xml

Aguardar próximo processamento

**Comment by botturam** [comment]
A marcação está sendo realizada com sucesso no ano corrente (2017) de MEDLINE, já disponível em homologação. Amanhã, 3f, 28/11, estará em produção.

verificar ID:

id:mdl-29094171

**Comment by botturam** [comment]
Processamento FULL-MEDLINE finalizado neste último fim de semana, dia 03/12/2107. Processamento do MarkAbstract realizado. Verificar exemplos:

http://pesquisa.bvsalud.org/portal/resource/pt/mdl-26377746 
http://pesquisa.bvsalud.org/portal/resource/pt/mdl-29094171
